### PR TITLE
Bitbucket utility for commenting on a PR

### PR DESCRIPTION
**Pull request by brjeter**
@oconnormi @LinkMJB

### CODE REVIEW

**Comment by LinkMJB** [comment]
@brjeter have you been able to test this on a PR already? The Jenkinsfile on the fork of the desired repo, would just need to source the fork of this repo, to take advantage of it. Let me know if that doesn't make any sense, or if you need any more information.

**Comment by brjeter** [comment]
@LinkMJB yes I've been testing it on a PR and am working out one last issue.

**Comment by brjeter** [comment]
Alright, I've cleaned all of the code up and have tested it to confirm that it works 🎉

**Review by LinkMJB — APPROVED** [review]

**Comment by LinkMJB** [comment]
Thank you for working on this @brjeter! Looks great!

**Review by AdamBurstynski — APPROVED** [review]

**Review by TonyMorrison — APPROVED** [review]
Code appears to be consistent with Brandan's stated purpose

**Pull request merged**
